### ISSUE TITLE
Altitude of the starting or ending point of an arc

### ISSUE THREAD

**Issue by BangNguyen1992** [vasturiano/react-globe.gl#122]
**Is your feature request related to a problem? Please describe.**
I have a globe that has 2 layers which are the HTML layer and the arc layer. The HTML layer is a starting point of multiple arcs line, is currently is above the altitude of the arc lines.
This is the problem currently
<img width="790" alt="image" src="https://user-images.githubusercontent.com/15904835/228125568-efed4905-10c0-463b-b2ab-29502af50935.png">

**Describe the solution you'd like**
 I want to have the HTML layer stays below the starting arc line altitude, might be adding two props like arcStartAltitude and arcEndAltitude.

**Describe alternatives you've considered**
Might be to add orderPriority prop to each layer

**Additional context**

**Comment by vasturiano** [comment]
@BangNguyen1992 thanks for reaching out.

It's the nature of the HTML layer to be always on top of any other WebGL based layer. Specifically because this is in fact a separate DOM element in the DOM altogether, that gets overlayed on top of the WebGL canvas.

But if what you need is to have WebGL dots that you can place behind the arcs, perhaps you'd be better off using the [points layer](https://github.com/vasturiano/react-globe.gl#points-layer). Those are represented as cylinders but you can give them low altitude so they resemble circular dots.

**Comment by BangNguyen1992** [comment]
Hello @vasturiano, thank you for your reply.

In the beginning, I am thinking of using the points layer as well, however, I need to be able to add styling to the marker and the points layer doesn't provide an option for that.

Do you have other suggestions to achieve this?

**Comment by vasturiano** [comment]
@BangNguyen1992 what type of styling are you thinking of?

If it's something that doesn't fit in the concept of a cylinder, you could use the [3d objects layer](https://github.com/vasturiano/react-globe.gl#3d-objects-layer) that will let you specify any WebGL object you'd like.
