### ISSUE TITLE
Hex layer overlapping Labels layer

### ISSUE THREAD

**Issue by benjaminlim00** [vasturiano/react-globe.gl#14]
**Describe the bug**
I am using two layers, the Hex polygon and Labels layer as shown in:
https://react-globe.vercel.app/

As you can see, when the labels of transactions pop up around every 3 seconds, it gets covered partially by he hex layer around it. Is there a way to set the z-index of the Labels layer to be higher?

**Expected behavior**
The labels should not have their text obscured

**Comment by vasturiano** [comment]
@benjaminlim00 thanks for reaching out.

In the webGL context of the globe there isn't really the concept of z-index. If an object is positioned behind another one it will be (at least partially) obscured by it.
For your case I'd recommend setting a higher altitude for the labels so that they don't overlap with the hex polygons.

**Comment by benjaminlim00** [comment]
Got it, thanks!
