### ISSUE TITLE
Bug: hexSideColor become black when removing the default AmbientLight

### ISSUE THREAD

**Issue by BangNguyen1992** [vasturiano/react-globe.gl#152]
**Describe the bug**
- After removing the default AmbientLight, the hex bin side color is black on the left side.

**To Reproduce**

1. Create a globe
2. Get the globe ref scene
3. Remove the default ambientLight
```js
      const defaultAmbientLight = scene.children.find(
        (item) => item instanceof AmbientLight,
      ) as AmbientLight;

      if (defaultAmbientLight) {
        scene.remove(defaultAmbientLight);
      }
```
4. Add hexBin layer
5. Set `hexSideColor` to a valid color

**Expected behavior**
The hexBin layer side color should be the same as what I defined

**Screenshots**
<img width="713" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/f70079b5-5c3d-430b-b928-c346de1291a1">

The wrong color on the left side
<img width="780" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/eaad1cec-9b2a-4c70-b0aa-f140a187f4e2">

The correct color on the right side
<img width="693" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/6e141caa-6532-4178-a988-3f0f6b86d432">

**Additional context**
- The reason I want to remove the default AmbientLight is that I want to control the light and shadow of the globe

<img width="725" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/10923fa5-d8ef-4dad-a5f9-694e8199f7e4">

**Comment by vasturiano** [comment]
@BangNguyen1992 the behavior you see is the expected behavior when you remove the ambient light. Essentially the only thing that's lighting up the back side of the objects from the direction of the directional light is the ambient light itself. Without it the back sides will have 0 light applied to it and will turn back. That's just the way the lighting works. Maybe a middle ground is to reduce the intensity of the ambient light instead of removing it.

**Comment by BangNguyen1992** [comment]
Hello @vasturiano, thank you for your reply.
Could we somehow add ambient light to a specific layer only?

**Comment by vasturiano** [comment]
@BangNguyen1992 I can't think of a way to do that. Not easily at least.
