### ISSUE TITLE
Globe autorotates very quickly if the page is in background for a while

### ISSUE THREAD

**Issue by mighty-phoenix** [vasturiano/react-globe.gl#157]
Hey @vasturiano 
If I switch to some other tab for a while after opening the globe, and switch back to it, the globe autorotates very quickly for a while.
Kindly see screen recording for reference.

https://github.com/vasturiano/globe.gl/assets/32777813/ad1ccbd0-4b57-48ab-b0a5-32c56e2992c1

How can I disable this behaviour and allow the globe to keep autorotating at the same speed as before?
Quick help would be highly appreciated.
Also, is there a way I can autorotate while playing the altitude animation(`globeRef.current.pointOfView({ altitude: 1.66 }, 1500);`)
Thanks! @vasturiano

**Comment by mighty-phoenix** [comment]
@vasturiano Understood.
Thanks. And what about my other question:
`Also, is there a way I can autorotate while playing the altitude animation(globeRef.current.pointOfView({ altitude: 1.66 }, 1500);)?`
Thanks!

**Comment by vasturiano** [comment]
@mighty-phoenix that's kind of tricky to do because both the controls autorotate and the altitude change via `pointOfView` are manipulating the position of the camera.

If the jump towards the new altitude is immediate it's fine, but when you animate the transition they start conflicting, resulting in auto-rotation stopping while the POV animation is running its course.

What you can do is try to compensate for the rotation halting by setting a target longitude at the end of the animation, so that it appears that the rotation continues. It's an approximation, but it might be sufficient for your use case.

Something like this:
```js
const world = globeRef.current;
world.pointOfView({ lng: world.pointOfView().lng - 45, altitude: 1.66 }, 1500)
```

Adjust the longitude delta (45º) to taste, depending on your auto rotation speed.
