### ISSUE TITLE
Change DirectionalLight

### ISSUE THREAD

**Issue by ilya-trifonov** [vasturiano/react-globe.gl#17]
Hey!
How can I change DirectionalLight of globe? I need to change default "intensity" to 0

I use next, but it doesn't work for me

```
// some code
const globeEl = useRef()

useEffect(() => {
    const scene = globeEl.current.scene()
    const directionalLight = new THREE.DirectionalLight(0xffffff, 0)
    scene.add(directionalLight, ambientLight)
}, [])

//some code
```

Need your help!

**Comment by vasturiano** [comment]
@ilya-trifonov it seems your code adds another light instead of modifying the existing one.

If you want to modify the existing light you can access it via `scene.children`:
<img width="877" alt="Screenshot 2020-10-20 at 22 59 18" src="https://user-images.githubusercontent.com/6784226/96679178-fd583200-1327-11eb-98f8-a1cc879abd8a.png">

As you can see you are able to access the directional light as `scene.children[2]`.

**Comment by ilya-trifonov** [comment]
Excellent! Works only outside useEffect.
```
if (globeEl.current !== undefined) {
    const scene = globeEl.current.scene()
    scene.children[1].intensity = 1.3
    scene.children[2].intensity = 0
}
```
Thanks!

**Comment by rohanbhangui** [comment]
@vasturiano might better to give the lights each a name that way they are easier to access via three js tools. For example: `const directionalLight = scene.getObjectByName('directionalLight'); directionalLight.intensity = 1.3`

**Comment by adamasturia** [comment]
> Excellent! Works only outside useEffect.
> 
> ```
> if (globeEl.current !== undefined) {
>     const scene = globeEl.current.scene()
>     scene.children[1].intensity = 1.3
>     scene.children[2].intensity = 0
> }
> ```
> 
> Thanks!

can you provide the whole code where this is being used? I tried it outside of useEffect, but the scene it loads only has the Mesh as its child
