### ISSUE TITLE
Is there a way to use threejs postprocessing on the globe?

### ISSUE THREAD

**Issue by edwmurph** [vasturiano/react-globe.gl#2]
**Is your feature request related to a problem? Please describe.**
I would like to be able to layer [post processing](https://threejs.org/docs/#examples/en/postprocessing/EffectComposer) over the globe.

**Describe the solution you'd like**
a good api for this would be if you exposed a passes config option that accepted an array of the post processing passes to apply during each render loop iteration.

**Describe alternatives you've considered**
without minor changes to the render loop logic, i dont think post processing layers are possible with this tool so i would have to recreate the tool.

**Additional context**
n/a

**Comment by vasturiano** [comment]
@edwmurph is this something that could be done externally by accessing the renderer using the `.renderer()` method, or would you need access to the animation loop?

**Comment by edwmurph** [comment]
i need access to the renderer, the scene and the camera when initializing the scene, which like you said are exposed. But then the render loop needs to be updated to call the render method of the composer, and this is not exposed.

e.g. to use the unreal bloom pass, first some code needs to be added during the scene initialization logic:
```
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js'

composer = new EffectComposer(this.renderer)
composer.addPass(new RenderPass(scene, camera))
composer.addPass(new UnrealBloomPass())
```

then some code needs to be added to the render loop logic:
```
renderer.render(scene, camera)
composer.render()
```


here’s a decent breakdown of how postprocessing works:
https://threejsfundamentals.org/threejs/lessons/threejs-post-processing.html

**Comment by edwmurph** [comment]
also i opened this issue before realizing the full stack of your tooling and am now currently using https://github.com/vasturiano/three-globe which also has this problem. would it be better if i closed this issue and reopened one in that repo?

**Comment by vasturiano** [comment]
@edwmurph `three-globe` shouldn't have this issue because it's just the `threejs` object. All the `rendered`, `camera` and `scene` scaffolding is left up to the consumer, so you are in full control on how the render animation cycle is done, and can therefore add postprocessing steps.

This functionality would have to be added to `globe.gl`, more specifically in this dependency: https://github.com/vasturiano/three-render-objects

I'm trying to imagine what the simplest API to allow this new functionality would be. Maybe exposing a postprocessing `composer` hook, like:
```
.composer(myPostProcessingComposer)
```

Which would be used to call `composer.render()`(if defined) on this line: https://github.com/vasturiano/three-render-objects/blob/master/src/three-render-objects.js#L90

**Comment by edwmurph** [comment]
Oh that’s right three-globe doesn’t have this issue so I no longer have a use case for this feature request and can close the issue. Thanks for your feedback!
