### ISSUE TITLE
[Question] How to update arcData without re-render

### ISSUE THREAD

**Issue by colin-riddell** [vasturiano/react-globe.gl#54]
**Is your feature request related to a problem? Please describe.**

I'd love to be able to update the arcData data without re-rendering. I'm pulling in data from a stream, and passing it down to the `arcData` prop, but this triggers a component re-render. So the arc animations start again every time a new element is added to the `arcData` prop. 

**Describe the solution you'd like**
I would love to be able to pass a stream of arcData to the component somehow? Maybe through a callback prop? Even if you could just point out where in the source code to look I could try and hack a solution for this? @vasturiano 

Ultimately I want to be able to add more data to the `arcsData` or `pointsData` that seamlessly is added and rendered in the canvas, but not cause it to re-render the entire `Globe` component.

**Describe alternatives you've considered**
I tried to queue the data into the `arcsData` prop, but ultimately every time something's added to that prop it triggers a re-render. My understanding is that it needs to because there's no way to easily add new data to the `arcsData`. Or is there?

Would using the non-react version of this make it possible/easier? (just thought of this)

**Additional context**
This is not as much of a feature request and more "is this possible? - if so show me roughly where to look in your source and i'll give it a try and maybe create a PR if I can find a good solution".

Thanks Kindly

**Comment by vasturiano** [comment]
@colin-riddell thanks for reaching out.

Whenever you add new arcs, if you include the existing arc object references in the array passed to `arcsData`, those existing arcs should not be interrupted or reset, but simply the new ones added. 

Basically, internally the framework performs an equality comparison on the array items that were previously included, and leaves them unaffected as there were already WebGL objects generated. This is done for performance reasons between updates actually, because re-generating many objects when potentially only a subset is new would be wasteful of resources. The added benefit is that their current rendering state (as in its animated position) is also not reset in the process.

What could be happening in your case is that you are somehow cloning the array items at every re-render before passing them back onto the globe component. And because the component performs reference comparisons, it is led to believe that all the arcs are new and therefore re-generates all the objects from scratch. This is not an uncommon thing to happen in the React world, and normally doing some memoization via hooks or similar prevents this cloning from happening.

Could you check if this may be the case in your app?

**Comment by colin-riddell** [comment]
Hi @vasturiano  - thanks so much for the detailed response. This was extremely valuable and this is exactly what was happening.
Kind Regards

**Comment by triblondon** [comment]
Hi there - sorry to barge into a closed issue, but I'm wondering how you do this in practice.  My code is updating the `arcData` array, and triggering a re-render of my component, but the globe doesn't appear to change visually.

```js
const GlobeAnimation = () => {
  const [arcs, setArcs] = useState([])
  const globeEl = useRef();

  useEffect(() => {
    globeEl.current.controls().enableZoom = false;
    globeEl.current.controls().autoRotate = true;
    globeEl.current.controls().autoRotateSpeed = 0.7;
    const stream = new Stream(SOURCE_URL)
    stream.on("event", async (newArc) => {
      setArcs(list => {
        const now = Date.now()
        while (list.length && now > (list[0].startTime + ANIMATION_TIME)) list.shift()
        if (list.length < MAX_HISTORY) list.push(newArc)
        return list
      })
    })
    stream.connect()
    return () => stream.close()
  }, []);

  return (
    <Globe
      ref={globeEl}
      globeImageUrl="//unpkg.com/three-globe/example/img/earth-night.jpg"
      arcsData={requests}
      arcColor={"color"}
      arcStroke={0.6}
      arcDashLength={1}
      arcDashGap={0}
      arcDashInitialGap={0}
      arcDashAnimateTime={ANIMATION_TIME}
      arcsTransitionDuration={0}
    />
  )
}
```

How do you update the arc data of an existing, already rendered Globe?

**Comment by vasturiano** [comment]
Easier with a repro link, but by looking at your code, the Globe doesn't appear to reference your `arcs`, but an undefined `requests`.
```jsx
arcsData={requests}
```

**Comment by triblondon** [comment]
Sorry 🤦  I edited the code to make it more generic for the post and missed that token.

I ended up using the globe.gl module, rather than the React wrapper, so I can call `globeInstance.arcsData`.  It's now working great!
