### ISSUE TITLE
How to capture the coordinates of the center place on earth based on camera view?

### ISSUE THREAD

**Issue by TheManFromEarth1** [vasturiano/react-globe.gl#73]
**Is your feature request related to a problem? Please describe.**
I want to get the country name when you either click or move to a specific country.

With polygons, the performance is not so good at the moment (~29). HexPolygons are better, but don't capture all edges.

As an alternative way, it should be faster if I check current long/lat and reverse engineer to get if any country is selected, and which.

**Describe the solution you'd like**
How can I show e.g. a red dot on the most center point based on camera, and grab the coordinates of that location?

Specific references I can read would help as well, I don't know where to start atm.

**Comment by vasturiano** [comment]
@TheManFromEarth1 thanks for reaching out.

You should be able to get the coordinates of the current camera vantage point (including latitude, longitude and altitude) anytime by invoking `.pointOfView()` (with no arguments). That will return an object in the following format:
```
{
  lat: 12.345,
  lng: -7.9113
  altitude: 3.5
}
```

As for setting some target symbol always on the center of the canvas, I would add a Three object as a child of the camera (that you can access via `.camera()`) so that it's attached to the camera instead of the globe. That way regardless of where the view point moves, that mark will always be fixed and visible.

If you're looking to add a red dot, you could try adding a small [red sphere](https://threejs.org/docs/#api/en/geometries/SphereGeometry).

**Comment by TheManFromEarth1** [comment]
Thank you very much. 

If anyone else stumbles upon this, I used this old library to do the reversing of coordinates to country.
It works very fast, frames don´t drop.

https://github.com/totemstech/country-reverse-geocoding
