### ISSUE TITLE
add specularMap

### ISSUE THREAD

**Issue by marvin-kolja** [vasturiano/react-globe.gl#8]
Hey @vasturiano,
I am currently working on a project where I have to create a globe and visualize data on it. I'm happy to use such a great lib, thanks to you. Since I'm new to JS and especially React it's hard for me to understand all the connections.

**Coming to why I created this request:** I would love to add a specular map for water reflection such as in this project [here](http://west77.ru/content/geoJSON/index.html).

Maybe there is an easy answer, then I'd love to hear it. 

Nevertheless, I took a deep look into your libaries and found the [globe.js](https://github.com/vasturiano/three-globe/blob/master/src/layers/globe.js) script of your [three-globe](https://github.com/vasturiano/three-globe) library. There you defined a `new THREE.Mesh` respectively a `new THREE.MeshPhongMaterial`. As far as I understood I'm not able to add anything to this material, because there are only defined variables for the bumpmap and texturemap. As I said before I would love to have one where I can add a 'specularImageUrl'.

I appreciate your response
Marvin

**Comment by vasturiano** [comment]
@marvin-kolja thanks for reaching out.

If you are referring to the light reflection in the image, the current globe material already does that.  You can notice that effect from this example (specially in the northern hemisphere since the light source is above the globe):
https://vasturiano.github.io/react-globe.gl/example/world-population/

You'd just need to add a globe (wrapping) image that includes the water with `globeImageUrl`, and potentially also `bumpImageUrl` for texture if you wish.

Another thing you can do to exacerbate the reflection effect is to add an additional light source. The example you mentioned appears to have a light source roughly above Turkey.

You can do that by extending the `scene`, for example:
```
const myLight = new THREE.DirectionalLight(0xffffff, 0.8);
myLight.position = new THREE.Vector3(1, 0, 0);

const myScene = globeRef.current.scene();
myScene.add(myLight);
```

**Comment by marvin-kolja** [comment]
@vasturiano Indeed there is a reflection happening with any texture defined for 'map'. However the [specular map](http://west77.ru/content/geoJSON/wateretopo.png) (black & white) can add additional reflection for contrast. 

According to the [three.js docs](https://threejs.org/docs/#api/en/materials/MeshPhongMaterial.specular):
> **.specular : Color**
> Specular color of the material. Default is a Color set to 0x111111 (very dark grey).

> This defines how shiny the material is and the color of its shine.

> **.specularMap : Texture**
> The specular map value affects both how much the specular surface highlight contributes and how 
> much of the environment map affects the surface. Default is null. 

In a previous test I did something like that:
```
var material = new THREE.MeshPhongMaterial({
        map:         THREE.ImageUtils.loadTexture('images/relief.jpg'),
        bumpMap:     THREE.ImageUtils.loadTexture('images/elev_bump_4k.jpg'),
        bumpScale:   0.005,
        specularMap: THREE.ImageUtils.loadTexture('images/wateretopo.png'),
        specular:    new THREE.Color('grey')
    });
```

The specular isn't necessary, but gives the globe a more realistic vibe, especially when using a texture map like [this](http://west77.ru/content/geoJSON/relief.jpg).

I could fork your three libraries and try to add this as an option.
Inside the globe.js mentioned above it could look like this:

```if (changedProps.hasOwnProperty('specularImageUrl')) {
      if (!state.specularImageUrl) {
        // No specular if no Image
      } else {
        new THREE.TextureLoader().load(state.specularImageUrl, texture => {
          globeMaterial.specularMap = texture;
          globeMaterial.specular = new THREE.Color('grey');
          globeMaterial.needsUpdate = true;

          !state.ready && (state.ready = true) && setTimeout(state.onReady);
        });
      }
    }```

Hopefully that helped to understand my question.

**Comment by vasturiano** [comment]
@marvin-kolja I see, thanks for the explanation.
I think it could then be useful to add a `specularImageUrl` prop like you mentioned. If you are so inclined, please open a PR on [three-globe](https://github.com/vasturiano/three-globe) and we can take it from there. 👍 

Also, if you just want to test, you can actually access the globe material from the `scene` in your component. It's a bit of a nested structure, but something like this would work:
```js
useEffect(() => {
  setTimeout(() => {
    const globeMaterial = globeEl.current.scene().children[3].children[0].children[0].children[0].material;
    globeMaterial.specularMap = /* your specular texture */;
  });
}, []);
```

Notice the `setTimeout` because the scene is populated assynchronously.

**Comment by marvin-kolja** [comment]
@vasturiano I'm very happy to hear this.

For sure the nested structure is not a persistance solution. 

I forked the three-globe repo and realized that the .specularMap property requieres the .specular property. I ended up with adding a bumpScale and shininess (How shiny the .specular highlight is), too. Since that wasn't our agreement I can undo those. Just tell me at the PR.

**Comment by marvin-kolja** [comment]
**Solution**
The specularMap can be added to the globe material by the new [globeMaterial ](https://github.com/vasturiano/react-globe.gl#globe-layer) method.
